### ISSUE TITLE
Support ! prefixed subfolder sounds

### ISSUE THREAD

**Issue by Cynosphere** [NonagonNetwork/sh#7]
https://github.com/Earu/neo-chatsounds/commit/6dce220b84dadab66e5bd53ea7b5c6a3f611ce01

love changing things without asking the general consensus of if this should be changed and notifying other people cause haha who uses chatsounds externally right? :>

**Comment by be195** [comment]
This is a weird feature, considering I have never seen any chatsound repositories utilize exclamation mark. On it.

**Comment by Cynosphere** [comment]
The first sounds using it: https://github.com/Metastruct/garrysmod-chatsounds/commit/0bff904285b928b05031a5ad501a9e912047689e

**Comment by be195** [comment]
What the hell lol

**Comment by be195** [comment]
I have just looked into this code and thought that it also has its own issues.

Logically it would make sense to use exclamation mark on the "sub-realm" folder itself (i.e. `valorant/!sage`), not the chatsound names. For example (or what I am confused about), how are you supposed to add multiple chatsounds with the same name into the same "sub-realm"? (See [`ssbb_sonic/sonicfx`](https://github.com/Metastruct/garrysmod-chatsounds/tree/0bff904285b928b05031a5ad501a9e912047689e/sound/chatsounds/autoadd/ssbb_sonic/sonicfx) to see what I am talking about.)

This is also not backwards compatible. It will not work on previous implementations of Chatsounds (goluwa implementation and Metastruct/garrysmod-chatsounds) without its modification.

But, eh, I will add this in.
